### PR TITLE
Config vor CircleCI 2.0

### LINKED ISSUE #49: Upgrade to CircleCI 2.0
After August 31, 2018, CircleCI 1.0 will [no longer be available](https://circleci.com/blog/sunsetting-1-0/).

@hiattp @citizen428

### PR DESCRIPTION
**Pull request by citizen428**
CircleCI 1.0 will be sunset on August 31st, 2018, so let's get this updated, closes #49.

### CODE REVIEW

**Comment by hiattp** [comment]
Oh yeah you articulated the same thing in the description. Why don't we just close this PR for now and revisit when 2 supports CD?

**Comment by citizen428** [comment]
Closing until Circle 2 becomes useful with Heroku.

**Comment by janklimo** [comment]
@citizen428 looking at [this](https://circleci.com/docs/2.0/deployment-integrations/#heroku) it looks like Heroku support is all good now? Haven't tried myself tho.

**Comment by citizen428** [comment]
Thanks for the info @janklimo, I got it to successfully build AND deploy now (for testing purposes I deployed the `circle-2` branch to Heroku `master` and later undid that change again).

So this should be ready now.

**Comment by citizen428** [comment]
I've configured everything to use the following workflow:

screen shot 2018-05-18 at 17 14 25

This means that after checking out the source code, `yarn install` and `bundle install` will run in parallel before then running the tests. Alas this required quite a few steps to be duplicated across the different jobs, but a lot of them don't do anything/very little when called repeatedly (I took the official demo workflows as a template).

Of course for a small template app like this the speedup is negligible (maybe it's even slightly slower), but for an actual app with quite a few gems and JS dependencies this should be quite a bit faster.

**Comment by citizen428** [comment]
Please don't merge this yet, there's one more thing I need to figure out, thanks!

**Comment by janklimo** [comment]
Mad props to @citizen428 this is awesome 🎉  I'll see if I manage to test it out on a real app this weekend and leave feedback.

**Comment by hiattp** [comment]
Cool LGTM, leaving to @citizen428 to round out and merge

**Pull request merged**
