### PR TITLE
add barnes to activate ruby language metrics

### PR DESCRIPTION
**Pull request by hiattp**
https://devcenter.heroku.com/articles/language-runtime-metrics-ruby#getting-started

### CODE REVIEW

**Comment by janklimo** [comment]
@hiattp we had this enabled for PG but we never got any value out of it. The charts it gives you look nice but I find they lack actionability, like if your object count goes up, why did it go up? Tools like New Relic or Scout give much more granular insights.

No harm in adding it, though. Anything particular you're hoping to use it for?

**Comment by hiattp** [comment]
Just noticed it was available and wanted to try it out 😬. No performance cost right? Maybe we just try it for a bit so I can see how useful or not it is

**Comment by hiattp** [comment]
Memory seems to be our biggest upcoming challenge so more information seems better than less atm

**Comment by janklimo** [comment]
Ok, let's try 👍 yes, there is 0 overhead, good to check it out.

**Pull request merged**
