### PR TITLE
Update rack_timeout.rb

### PR DESCRIPTION
**Pull request by mrmattwright**
Am guessing an error here as the Gemfile has RackTimeout in the production group, also this would make sense in the context of the comments. Unregister the logger unless in development mode. 

Side note: the app won't boot without some changes here. You get an error:

```
/Users/person/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant': uninitialized constant Rack::Timeout (NameError)
```

### CODE REVIEW

**Comment by hiattp** [comment]
Thanks for the PR @mrmattwright! It looks like either (a) that line should be removed completely since Rack::Timeout isn't in development anyway or (b) Rack::Timeout shouldn't be limited to the production group. @janklimo I think that was your change so feel free to make the call there. cc @citizen428

**Comment by hiattp** [comment]
Ah maybe not, git blame suggests @citizen428. Anyway...I'm sure you both have opinions on this :). I'm a bit ambivalent

**Comment by janklimo** [comment]
@hiattp @mrmattwright this has been borrowed from Pathgather where the gem is not limited to production. Now that I think about it, it makes no sense to have it outside of production so the last line is not needed. In that case, the initializer as a whole is not needed, we just need to update readme to explain `Rack::Timeout` config via environment vars and their defaults.

**Comment by janklimo** [comment]
@mrmattwright I suggest we remove `config/initializers/rack_timeout.rb` altogether. `rack-timeout` is only relevant (and scoped to in gemfile) in production.

Can you please add a line to the [readme](https://github.com/lockstep/rails_new#environment-variables), including `RACK_TIMEOUT_SERVICE_TIMEOUT` in the table with a short note about [what it's for and what's the default](https://github.com/heroku/rack-timeout/blob/master/doc/settings.md)?

**Comment by citizen428** [comment]
Thanks for this @mrmattwright. I'll take it from here.

@hiattp @janklimo For context, Matt's a friend of mine who recently started a new project from our template.

**Pull request closed without merging**
