### PR TITLE
Upgrade to sentry-ruby

### PR DESCRIPTION
**Pull request by panitanp11**
- gem`sentry-raven` removed
- gem `sentry-rails`, ~`sentry-ruby`~, and `sentry-sidekiq` added
- removed `SentryWorker`

### CODE REVIEW

**Comment by janklimo** [comment]
@panitanp11 Thank you for this! Is sentry-ruby necessary when sentry-rails is installed?

**Comment by panitanp11** [comment]
Thank you @janklimo.
You're right. sentry-ruby is unnecessary. I'll update the PR.

**Comment by panitanp11** [comment]
Last push was to remove `sentry-ruby`.

**Comment by janklimo** [comment]
Thank you @panitanp11 👏

**Pull request merged**
