### PR TITLE
Force using node version ^12.4.0

### PR DESCRIPTION
**Pull request by karunsiri**
Set node version in the engines key using semver `^12.4.0` (>=12.4.0 and <13.0.0).

When running `yarn`, if the installed node version doesn't meet the specified semver, Yarn will raise error.

### CODE REVIEW

**Comment by karunsiri** [comment]
@hiattp It doesn't auto update Node. It just checks against the installed/loaded version. You need to either reinstall node yourself or use a version manager to load new working version. For example, if you install `12.4.5` that meets the required semver, it will stays at the version until you explicitly install newer version.

**Comment by janklimo** [comment]
@karunsiri I think @hiattp is suggesting updating it to 12, but not higher than that. We've had cases in the past where a flexible definition like this would break the build on Heroku when a new Node version is released. So typically, we want to restrict the upper bound by something we know won't break.

**Comment by karunsiri** [comment]
@hiattp @janklimo Locked Node version from 12.4.0 to 13.0.0, 13.0.0 excluded.

**Comment by hiattp** [comment]
@karunsiri @janklimo Looks like we might have to set an explicit node version in the circle config as well, it pulls v10 by default afaict. @karunsiri did you get the invite to join this repo/org? If you submit a PR in this repo directly instead of a fork it will run circle to confirm the build works 👍

**Comment by janklimo** [comment]
The way I see it we have two options:

1. Keep our config pegged to the _LTS_ version of Node. [This is what](https://github.com/circleci/circleci-images/issues/188#issuecomment-386888248) comes bundled together with the ruby image provided by Circle (that's why we're seeing v10 being used). Advantage: use default Circle images, use what's considered to be mainstream version of Node, low effort. Downsides: not using the latest, probably miss out on some shiny new features.
1. Fix the config to use the _current_ Node version. Downside: need to build our own Docker image (?), possibly slower builds (?), more maintenance. Advantage: latest everything, flexible.

I'm thinking 1) gives us the most value for the least work. 2) is nice to have but comes with extra work which might not be needed. Just my 2 cents, @karunsiri please think about it and let us know if there are other ways/aspects I missed.

**Comment by hiattp** [comment]
Interesting. Well aside from feeling a bit beholden to the circleci gods I don't mind pegging to the LTS that is pulled in with the ruby releases. IIRC the primary motivation for this ticket was to avoid surprise node updates on builds and ideally to get everyone on the same version (locally, test env and deployed).

So it sounds like the best thing to do is keep our template version pegged to the active LTS. When we update the ruby version (which happens fairly frequently) at some point we'll see yarn semver failures because the new ruby container will be pulling in a new node engine, so we'll be spurred to update our node expectations at that time. v12 is coming in October anyway, not too far off.

So seems like we should be using "^10.16.0", we cool with that?

**Comment by karunsiri** [comment]
@hiattp I don't get any joining email. I remember pushing code and opening a PR her a few months ago, but I cannot do it now. I think I don't have write permissions anymore. Could you check please? Thank you 👍

**Comment by hiattp** [comment]
@karunsiri go here: https://github.com/lockstep, you should be able to accept the invite and join the repo directly

**Pull request merged**
