### PR TITLE
Add system tests

### PR DESCRIPTION
**Pull request by citizen428**
Rspec now has WIP support for the systems tests added in Rails 5.1. This is cool for various reasons:

* Almost no setup required
* Automatically creates a screenshot on failure and saves it in `tmp/screenshots`

Here's an example of a failed spec run:

screen shot 2017-06-28 at 11 56 33

If you're used to writing feature specs, there's not much you need to change. Specs move from `spec/feature` to `spec/system` and the outermost `feature` call needs to be replaced by a `describe` so we don't override the inferred spec type. See example included in this PR.

I think I'd like to wait for the gems to stabilize a bit more before merging this into the main branch, but I wanted to give you a preview.

### CODE REVIEW

**Comment by janklimo** [comment]
@citizen428 this is sweet! Yeah I'd wait for the official releases of the gems in question. I also noticed you removed DatabaseCleaner a while back, so we can remove references to that and Poltergeist in the readme as well.

**Comment by citizen428** [comment]
Thanks @janklimo, I updated the README.

**Comment by citizen428** [comment]
@hiattp Yes, I hope this will stabilize quickly so I can merge it into `master`.

**Comment by citizen428** [comment]
Just an update, this is waiting for Rails 5.1.4, which will ship a minor improvement the Rspec guys are waiting for to finally get this merged.

**Pull request merged**
