### PR TITLE
Add rescue_from for expired sessions

### LINKED ISSUE #64: Handle ActionController::InvalidAuthenticityToken
I see this in virtually every (non-API) application—someone leaves their browser open for a long time and then tries to submit a form (or log out), and they see an error due to an invalid authenticity token. It seems like we should at least rescue this by default and show a default flash message. Otherwise it just pops up eventually in every production app and we deal with it as it arises, which isn't a good experience for our clients or their users

### PR DESCRIPTION
**Pull request by citizen428**
Closes #64

### CODE REVIEW

**Comment by hiattp** [comment]
it's possible that the session expired but I think it's also possible that the session is still valid _but_ the authenticity token expired. that sound right? if so we'll need this to be a bit more generic (redirect back instead of to the new session page, change language to something more like please try your request again...thoughts?)

**Comment by citizen428** [comment]
As long as you used cookie based sessions the token only becomes invalid if you lose your session cookie, either by deleting it or because it expired. But maybe doing it a more generic way still doesn't hurt? How about this?

```ruby
rescue_from ActionController::InvalidAuthenticityToken do
  flash[:notice] = "Please try again."
  redirect_back fallback_location: '/', allow_other_host: false
end

**Comment by hiattp** [comment]
Ok given that I'd lean towards a variation on your original, "Your session expired, please try again." and then probably makes sense for the fallback location to be `root_path` or no?

**Comment by citizen428** [comment]
@hiattp Of course, was just quick and dirty, updated now.

**Pull request merged**
