### PR TITLE
Add jsonapi-rails

### LINKED ISSUE #41: Decide on serialization method
Background: [What's happening to AMS](https://github.com/rails-api/active_model_serializers#whats-happening-to-ams)

They themselves seem to suggest that [jsonapi-rb](http://jsonapi-rb.org/) could be a good alternative, so I'm interested in opinions.

Please check out the docs and provide feedback on whether or not we should move forward with this:

http://jsonapi-rb.org/guides/getting_started/rails.html

For reference: I always liked JSON API and built similar structures myself before it became a thing, so might be biased.

### PR DESCRIPTION
**Pull request by citizen428**
Closes #41

### CODE REVIEW

**Comment by hiattp** [comment]
Yep I like this, I've added it to afterthird in https://github.com/OneHatched/after_third/commit/1bccd76f3812911c199576295e32de1826463a9b. It's not a drop-in replacement but close enough, and follows the http://jsonapi.org conventions more aggressively than AMS.

I do prefer the AMS serializer naming convention so I kept it. It seems like `PostSerializer` in `app/serializers` follows rails conventions more closely than `SerializablePost` in a similar directory. Thoughts on making it our default? cc #41

**Comment by citizen428** [comment]
The name would be a possibility. What do you want to do for the `Deserializable` classes though? `PostDeserializer` in `app/serializers`? Or the same class name in `app/deserializers`?

**Comment by hiattp** [comment]
yeah, I'd probably look for it in `app/deserializers`. it does strike me as a bit inconvenient to format json this way if we are interacting with our own API (e.g. nest an object we are POSTing to the server like `{ data: { attributes: { ... } }` thus necessitating a deserialization step before it hits rails. but I also don't like the asymmetry of passing the object in one format and receiving it in another. are people really adopting this data/attributes format for sent and received data in APIs?

**Comment by citizen428** [comment]
> are people really adopting this data/attributes format for sent and received data in APIs?

Depends on how much they want to follow the spec. Before JSON API became a thing I had my own format that was somewhat similar (far less evolved though), and I tried to keep it symmetric. Realistically speaking one would probably use [jsonapi-serializer](https://github.com/SeyZ/jsonapi-serializer) or similar on the JS side, not manually build the JSON structure. But I guess this can be decided on a case to case basis.

I agree that the name change feels more Rails-y, we just need to make sure to document in properly since it deviates from the standard.

**Comment by citizen428** [comment]
@hiattp Ready now. Give it a once-over, then merge if you feel like it.

**Pull request merged**
